apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-claim
spec:
  storageClassName: todo-image-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
