apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cron
              image: todo-cron:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_BACKEND_URL
                  value: "http://todo-backend-svc:2345"
          restartPolicy: OnFailure
