apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: project
data:
  PORT: "8080"
  TODO_BACKEND_URL: "http://todo-backend-svc:2345"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_PATH: "files/image.jpg"
  CACHE_TIME: "600"
