apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-image-claim

      containers:
        - name: todo-app
          envFrom:
            - configMapRef:
                name: todo-config
          image: todo-app:2.6
          env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:2345"
          volumeMounts:
            - name: image-storage
              mountPath: /app/files
