apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          envFrom:
            - configMapRef:
                name: todo-config
          image: todo-backend:2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
