apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-storage
          emptyDir: {}

        - name: config-volume
          configMap:
            name: log-output-config

      containers:
        - name: log-generator
          image: log-output:2.5
          command: ["python3", "generator.py"]

          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

          volumeMounts:
            - name: log-storage
              mountPath: /usr/src/app/files

            - name: config-volume
              mountPath: /usr/src/app/config

        - name: log-reader
          image: log-output:2.5
          command: ["python3", "reader.py"]
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

          volumeMounts:
            - name: log-storage
              mountPath: /usr/src/app/files

            - name: config-volume
              mountPath: /usr/src/app/config
